version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "9000:9000"
    environment:
      # Override các giá trị cho Eureka để các container giao tiếp với nhau:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
      EUREKA_INSTANCE_HOSTNAME: "api-gateway"
      # Nếu cần, bạn có thể override các biến khác từ application.properties
    networks:
      - gateway-network

networks:
  gateway-network:
    driver: bridge
