version: '3.8'

services:
  eureka-server:
    build: .
    container_name: eureka-server
    ports:
      - "8761:8761"
    # Nếu không có biến môi trường cần override, bạn có thể xóa dòng này hoặc đặt nó thành {}
    # environment: {}
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
