version: "3.8"

services:
  # 1. Eureka Server
  eureka-service:
    container_name: eureka-service
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservice-net

  # 2. API Gateway
  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - eureka-service
    environment:
      EUREKA_INSTANCE_HOSTNAME: api-gateway
      # Ví dụ nếu muốn chạy profile "docker" trong Spring:
      # SPRING_PROFILES_ACTIVE: docker
    networks:
      - microservice-net

  # 3. Auth Service
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - eureka-service
      - mysql
    environment:
      # Kết nối tới MySQL container (tên "mysql")
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      # Cấu hình eureka
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      EUREKA_INSTANCE_HOSTNAME: auth-service

    networks:
      - microservice-net

  # 4. MySQL Database
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
      # Không nên dùng MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservice-net

networks:
  microservice-net:

volumes:
  mysql_data:
