# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x61i.proto\x12\x02\x61i\"\x1e\n\nAIResquest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x1c\n\nAIResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t22\n\tAIService\x12%\n\x03\x41sk\x12\x0e.ai.AIResquest\x1a\x0e.ai.AIResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRESQUEST']._serialized_start=16
  _globals['_AIRESQUEST']._serialized_end=46
  _globals['_AIRESPONSE']._serialized_start=48
  _globals['_AIRESPONSE']._serialized_end=76
  _globals['_AISERVICE']._serialized_start=78
  _globals['_AISERVICE']._serialized_end=128
# @@protoc_insertion_point(module_scope)
