#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  creationTimestamp: null
#  labels:
#    io.kompose.service: grafana-claim0
#  name: grafana-claim0
#  namespace: default
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 100Mi
#status: {}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

