global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081', 'order-service:8086', 'payment-service:8087']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
