version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth-db
    restart: unless-stopped  # Chỉ restart nếu service bị dừng do lỗi
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth-network
    deploy:
      resources:
        limits:
          cpus: "0.5"  # Chỉ dùng tối đa 50% của 1 CPU core
          memory: "512M"  # Giới hạn MySQL sử dụng 512MB RAM
    command: --default-authentication-plugin=mysql_native_password --max_connections=20 --table_open_cache=50
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    build: .
    container_name: auth-service
    restart: unless-stopped  # Chỉ restart nếu service bị dừng do lỗi
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: z6NcAZXi9+HYC6ByT+uG+73PdgAHQomW0s7EnpAY+Ns=
    ports:
      - "8081:8081"
    networks:
      - auth-network
    deploy:
      resources:
        limits:
          cpus: "0.3"  # Auth Service chỉ dùng 30% 1 CPU core
          memory: "256M"  # Giới hạn RAM tối đa là 256MB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:

networks:
  auth-network:
    driver: bridge
