version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - auth-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    command: --default-authentication-plugin=mysql_native_password --max_connections=100 --table_open_cache=100
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    build:
      context: C:/musical-microservice/auth-service
      dockerfile: Dockerfile
      args:
        JAR_FILE: target/auth-service.jar  # Định nghĩa JAR file sẽ copy vào Docker
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/auth_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      JWT_SECRET: z6NcAZXi9+HYC6ByT+uG+73PdgAHQomW0s7EnpAY+Ns=
    ports:
      - "8081:8081"
    networks:
      - auth-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:

networks:
  auth-network:
    driver: bridge
