name: CI/CD to Minikube on Personal Ubuntu

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building and pushing: $SERVICE"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest ./$SERVICE
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
          done

      - name: Set Minikube context and Deploy to Minikube
        run: |
          kubectl config use-context minikube
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Deploying $SERVICE..."
            if kubectl get deployment "$SERVICE" -n default &>/dev/null; then
              echo "Deployment $SERVICE exists, updating image..."
              kubectl set image deployment/"$SERVICE" "$SERVICE"=${{ secrets.DOCKER_USERNAME }}/"$SERVICE":latest -n default
              kubectl rollout restart deployment/"$SERVICE" -n default
            else
              echo "Creating deployment for $SERVICE..."
              kubectl create deployment "$SERVICE" --image=${{ secrets.DOCKER_USERNAME }}/"$SERVICE":latest -n default
              kubectl expose deployment "$SERVICE" --type=ClusterIP --port=80 -n default
            fi
          done

      - name: Logout from Docker Hub
        run: docker logout
