name: Build, Push, Cleanup, and Deploy to AWS EKS

on:
  push:
    branches:
      - master  # Auto chạy khi có commit vào nhánh master
  schedule:
    - cron: '0 0 * * *'  # Chạy cleanup hàng ngày vào 00:00 UTC
  workflow_dispatch:  # Cho phép chạy thủ công nếu cần

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building and pushing: huutai2403/$SERVICE:latest"
            docker build -t huutai2403/$SERVICE:latest --file $SERVICE/Dockerfile $SERVICE
            docker push huutai2403/$SERVICE:latest
          done

      - name: Logout from Docker Hub
        run: docker logout

  cleanup:
    runs-on: ubuntu-latest
    needs: build-and-push  # Cleanup sau khi build & push thành công

    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Delete old images (giữ lại 3 phiên bản mới nhất)
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          TAGS_TO_KEEP=3

          for SERVICE in "${SERVICES[@]}"; do
            ALL_TAGS=$(curl -s -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
              "https://hub.docker.com/v2/repositories/huutai2403/$SERVICE/tags/" | jq -r '.results | sort_by(.last_updated) | .[].name')

            TAGS_TO_DELETE=$(echo "$ALL_TAGS" | head -n -$TAGS_TO_KEEP)

            for TAG in $TAGS_TO_DELETE; do
              curl -X DELETE -u "${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }}" \
                "https://hub.docker.com/v2/repositories/huutai2403/$SERVICE/tags/$TAG/"
              echo "Deleted: huutai2403/$SERVICE:$TAG"
            done
          done

      - name: Logout from Docker Hub
        run: docker logout

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: build-and-push  # Chạy deploy sau khi build & push thành công

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1  # Singapore

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name my-cluster --region ap-southeast-1

      - name: Deploy Services to AWS EKS
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Applying deployment for $SERVICE..."
            kubectl apply -f k8s/$SERVICE-deployment.yaml || echo "⚠️ Lỗi khi apply $SERVICE, kiểm tra lại YAML"
            echo "Updating Kubernetes Deployment for $SERVICE..."
            kubectl set image deployment/$SERVICE $SERVICE=huutai2403/$SERVICE:latest -n default || echo "⚠️ Lỗi khi update image $SERVICE"
            kubectl rollout restart deployment $SERVICE -n default
          done
