name: CI/CD to Minikube on Docker Desktop

on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Building and pushing: $SERVICE"
            docker build -t ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest ./$SERVICE
            docker push ${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest
          done

      - name: Start Minikube
        run: |
          if ! minikube status &>/dev/null; then
            echo "Starting Minikube..."
            minikube start --driver=docker
          else
            echo "Minikube is already running."
          fi
          kubectl config use-context minikube

      - name: Apply Kubernetes Manifests
        run: |
          echo " Applying all Kubernetes manifests..."
          kubectl apply -f k8s/

      - name: Update Deployment Images
        run: |
          SERVICES=("eureka-service" "api-gateway" "auth-service" "product-service" "user-service")
          for SERVICE in "${SERVICES[@]}"; do
            echo "Updating deployment image for: $SERVICE"
            if kubectl get deployment "$SERVICE" -n default &>/dev/null; then
              kubectl set image deployment/"$SERVICE" "$SERVICE"=${{ secrets.DOCKER_USERNAME }}/"$SERVICE":latest -n default || true
              kubectl rollout restart deployment/"$SERVICE" -n default
            else
              echo "Deployment $SERVICE not found, skipping update."
            fi
          done

      - name: Logout from Docker Hub
        run: docker logout
